document.writeln("<!DOCTYPE html>");
document.writeln("<!-- saved from url=(0021)https://app-wdxc.com/ -->");
document.writeln("<html style=\"font-size: 100px;\"><head design-width=\"750\"><meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">");
document.writeln("");
document.writeln("<meta name=\"viewport\" content=\"width=device-width,minimum-scale=1.0,maximum-scale=1.0,user-scalable=no\">");
document.writeln("<meta name=\"apple-mobile-web-app-capable\" content=\"yes\">");
document.writeln("<meta name=\"apple-mobile-web-app-status-bar-style\" content=\"black\">");
document.writeln("<meta name=\"format-detection\" content=\"telephone=no\">");
document.writeln("<title>App Download</title>");
document.writeln("<link rel=\"stylesheet\" href=\"css/reset.css\"><!--重置样式-->");
document.writeln("<link rel=\"stylesheet\" href=\"css/style.css\"><!--页面样式-->");
document.writeln("<link rel=\"stylesheet\" href=\"css/swiper.min.css\">");
document.writeln("<script src=\"js/auto-size.js\"></script><style>@media screen and (min-width:750px){.center{width:750px;margin-left:-375px;left:50%;}}</style><!--设置字体大小-->");
document.writeln("</head>");
document.writeln("<body ontouchstart=\"\" onmouseover=\"\" style=\"cursor: pointer;\">");
document.writeln("    <div class=\"mobile-wrap center\">");
document.writeln("        <main>");
document.writeln("            <div class=\"appItem\">");
document.writeln("                <div class=\"left\"><img src=\"images/logo.png\" alt=\"image\"></div>");
document.writeln("                <div class=\"right\">");
document.writeln("                    <strong>BaiHuo<span>18+</span></strong>");
document.writeln("                    <p>Similar ranking list #1</p>");
document.writeln("                    <div class=\"installBox\">");
document.writeln("                        <a class=\"down\" href=\"javascript:;\">Free installation</a>");
document.writeln("                        <a class=\"doubt\" href=\"javascript:;\">?</a>");
document.writeln("                    </div>");
document.writeln("                </div>");
document.writeln("                <div class=\"appTip\">");
document.writeln("                    <div class=\"score\">");
document.writeln("                    <div class=\"star\">4.9 ★★★★★<var></var></div>");
document.writeln("                        <p>29,613 Scores</p>");
document.writeln("                    </div>");
document.writeln("					<div class=\"centerBox\">");
document.writeln("						<b>536,726+</b>");
document.writeln("						<p>install</p>");
document.writeln("					</div>");
document.writeln("                    <div class=\"age\">");
document.writeln("                        <b>18+</b>");
document.writeln("                        <p>Age</p>");
document.writeln("                    </div>");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("        </main>");
document.writeln("             ");
document.writeln("");
document.writeln("           <main>");
document.writeln("            <div class=\"comment\">");
document.writeln("                <strong class=\"publicTitle\">Scoring and comments</strong>");
document.writeln("                <div class=\"left\">");
document.writeln("                    <b>4.9</b>");
document.writeln("                    <p>Full score 5 points</p>");
document.writeln("                </div>");
document.writeln("                <div class=\"right\">");
document.writeln("                    <div class=\"star_row\">");
document.writeln("                        <span class=\"s1\"><i></i></span>");
document.writeln("                        <div class=\"lineBox\"><var class=\"v1\"></var></div>");
document.writeln("                    </div>");
document.writeln("                    <div class=\"star_row\">");
document.writeln("                        <span class=\"s2\"><i></i></span>");
document.writeln("                        <div class=\"lineBox\"><var class=\"v2\"></var></div>");
document.writeln("                    </div>");
document.writeln("                    <div class=\"star_row\">");
document.writeln("                        <span class=\"s3\"><i></i></span>");
document.writeln("                        <div class=\"lineBox\"><var class=\"v3\"></var></div>");
document.writeln("                    </div>");
document.writeln("                    <div class=\"star_row\">");
document.writeln("                        <span class=\"s4\"><i></i></span>");
document.writeln("                        <div class=\"lineBox\"><var class=\"v4\"></var></div>");
document.writeln("                    </div>");
document.writeln("                    <div class=\"star_row\">");
document.writeln("                        <span class=\"s5\"><i></i></span>");
document.writeln("                        <div class=\"lineBox\"><var class=\"v5\"></var></div>");
document.writeln("                    </div>");
document.writeln("                    <p>29,613 Scores</p>");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("          ");
document.writeln("            <div class=\"appInfo\">");
document.writeln("                <strong class=\"publicTitle\">information</strong>");
document.writeln("                <div class=\"box\">");
document.writeln("                    <ul>");
document.writeln("                        <li>");
document.writeln("                            <span>size</span>");
document.writeln("                            <p>28.6 MB</p>");
document.writeln("                        </li>");
document.writeln("                        <li>");
document.writeln("                            <span>compatibility</span>");
document.writeln("                            <p>IOS 8.0 or higher is required to be compatible with iPhone, iPad and Android</p>");
document.writeln("                        </li>");
document.writeln("                        <li>");
document.writeln("                            <span>language</span>");
document.writeln("                            <p>English</p>");
document.writeln("                        </li>");
document.writeln("                        <li>");
document.writeln("                            <span>Age classification</span>");
document.writeln("                            <p>18+</p>");
document.writeln("                        </li>");
document.writeln("                        <li>");
document.writeln("                            <span>Copyright</span>");
document.writeln("                            <p>© 2025 Baihuo Inc</p>");
document.writeln("                        </li>");
document.writeln("                        <li>");
document.writeln("                            <span>Price</span>");
document.writeln("                            <p>free</p>");
document.writeln("                        </li>");
document.writeln("                        <li>");
document.writeln("                            <span>Privacy Policy</span>");
document.writeln("                            <p>✋</p>");
document.writeln("                        </li>");
document.writeln("                    </ul>");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("        </main>");
document.writeln("        <div class=\"footer\">");
document.writeln("            <p>Disclaimers：</p><p class=\"\"> This website only provides developers with download, installation and hosting of apps. App developers are responsible for the content and operation related matters in the app, which has nothing to do with this website</p>");
document.writeln("           ");
document.writeln("        </div>");
document.writeln("        <div class=\"pup\">");
document.writeln("            <div class=\"guide\">");
document.writeln("                <i class=\"colse\"></i>");
document.writeln("                <div class=\"pics\">");
document.writeln("                    <div class=\"swiper-container\">");
document.writeln("                        <div class=\"swiper-wrapper\">");
document.writeln("                             <div class=\"swiper-slide\">");
document.writeln("                                <div class=\"pic\"><img src=\"images/0df0c_0_600_411.jpg\" alt=\"\"></div>");
document.writeln("                                <div class=\"text\">Installation boot<br>Step 1  Allow opening configuration description file</div>");
document.writeln("                             </div>");
document.writeln("                             <div class=\"swiper-slide\">");
document.writeln("                                <div class=\"pic\"><img src=\"images/9179e_3_600_411.jpg\" alt=\"\"></div>");
document.writeln("                                <div class=\"text\">Step 2  Open Settings and tap [Profile Downloaded] or open Settings > General > VPN & Device Management > SellerCenter</div>");
document.writeln("                             </div>");
document.writeln("                             <div class=\"swiper-slide\">");
document.writeln("                                <div class=\"pic\"><img src=\"images/d3c74_2_600_411.jpg\" alt=\"\"></div>");
document.writeln("                                <div class=\"text\">Installation boot<br>Step 3  Click [Install] and enter the lock screen password to complete </div>");
document.writeln("                             </div>");
document.writeln("                           ");
document.writeln("                        </div>");
document.writeln("                        <div class=\"swiper-pagination\"></div>");
document.writeln("                    </div>");
document.writeln("                </div>");
document.writeln("                <div class=\"smallTip\"><a href=\"https://tkcng.com/www\">What is a description file?</a></div>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("    ");
document.writeln("    <div class=\"pupPic\"><img src=\"images/5cbc4_5_1242_2007.png\" alt=\"\"></div>");
document.writeln("    </div><!--mobile_wrap-->");
document.writeln("");
document.writeln("    <script src=\"js/jquery-2.2.4.min.js\"></script><!--jQ库-->");
document.writeln("    <script src=\"js/swiper-4.2.0.min.js\"></script><!--轮播库-->");
document.writeln("    <script>");
document.writeln("        $(\"body\").css(\"cursor\",\"pointer\");");
document.writeln("        ");
document.writeln("        var ua = navigator.userAgent.toLowerCase();");
document.writeln("        var Sys = {};");
document.writeln("        var s;");
document.writeln("        (s = ua.match(/version\/\//([\/\/d.]+).*safari/)) ? Sys.safari = s[1] : 0;");
document.writeln("");
document.writeln("");
document.writeln("        //判断设备是否为iPhone");
document.writeln("        if (/(iPhone|iPad|iPod|iOS)/i.test(ua)) {  ");
document.writeln("            if (Sys.safari) {");
document.writeln("                $(\".down\").attr(\"href\",\'app/ios.mobileconfig\');");
document.writeln("				");
document.writeln("				if(isIOS17OrHigher()){");
document.writeln("					");
document.writeln("					$(\".down\").click(function(event) {");
document.writeln("					    setTimeout(function(){");
document.writeln("					        $(\".pup\").fadeIn();");
document.writeln("					        var swiper = new Swiper(\'.swiper-container\',{");
document.writeln("					            loop: true,");
document.writeln("					            pagination: {");
document.writeln("					                el: \'.swiper-pagination\',");
document.writeln("					            },");
document.writeln("					        });");
document.writeln("					    },2500)");
document.writeln("					});");
document.writeln("					");
document.writeln("				}else{");
document.writeln("					$(\".down\").click(function(event) {");
document.writeln("					    setTimeout(function(){");
document.writeln("					        if( confirm){");
document.writeln("					            location.href = \"static/install.mobileprovision\";");
document.writeln("					        }");
document.writeln("					    },2500)");
document.writeln("					});");
document.writeln("				}");
document.writeln("				");
document.writeln("                ");
document.writeln("                //打开引导弹窗");
document.writeln("                $(\".doubt\").click(function(event) {");
document.writeln("                    $(\".pup\").fadeIn();");
document.writeln("                    var swiper = new Swiper(\'.swiper-container\',{");
document.writeln("                        loop: true,");
document.writeln("                        pagination: {");
document.writeln("                            el: \'.swiper-pagination\',");
document.writeln("                        },");
document.writeln("                    });");
document.writeln("                });");
document.writeln("            }else{");
document.writeln("                $(\"body\").click(function(event) {");
document.writeln("                    $(\".pupPic\").show();");
document.writeln("                 });");
document.writeln("            }");
document.writeln("        } ");
document.writeln("        //判断是否QQ内置浏览器");
document.writeln("        else if(ua.indexOf(\' qq\')>-1 && ua.indexOf(\'mqqbrowser\') <0){");
document.writeln("            $(\".down\").attr(\"href\",\'###\');");
document.writeln("            $(\"body\").click(function(event) {");
document.writeln("                $(\".pupPic\").show();");
document.writeln("             });");
document.writeln("        }");
document.writeln("        //判断Android");
document.writeln("        else if (/(Android)/i.test(ua)) {   ");
document.writeln("            $(\".down\").attr(\"href\",\'app/android.apk\');");
document.writeln("            //打开引导弹窗");
document.writeln("            // $(\".doubt\").click(function(event) {");
document.writeln("            //     $(\".pup\").fadeIn();");
document.writeln("            //     var swiper = new Swiper(\'.swiper-container\',{");
document.writeln("            //         loop: true,");
document.writeln("            //         pagination: {");
document.writeln("            //             el: \'.swiper-pagination\',");
document.writeln("            //         },");
document.writeln("            //     });");
document.writeln("            // });");
document.writeln("        }");
document.writeln("        //在微信中打开");
document.writeln("        if (ua.match(/MicroMessenger/i) == \"micromessenger\") {");
document.writeln("            $(\".down\").attr(\"href\",\'###\');");
document.writeln("            $(\"body\").click(function(event) {");
document.writeln("                $(\".pupPic\").show();");
document.writeln("             });");
document.writeln("        }");
document.writeln("        ");
document.writeln("        //关闭弹窗");
document.writeln("        $(\".colse\").click(function(event) {");
document.writeln("            $(\".pup\").fadeOut();");
document.writeln("        });");
document.writeln("");
document.writeln("        //判断是否高于iOS17");
document.writeln("		function isIOS17OrHigher() {");
document.writeln("		  const ua = navigator.userAgent;");
document.writeln("		  const iosMatch = ua.match(/OS (\/\/d+)_/);");
document.writeln("		  return iosMatch ? parseInt(iosMatch[1], 10) >= 17 : false;");
document.writeln("		}");
document.writeln("    </script>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("</body></html>");